server {
    listen 80 default_server;
    server_name lv10.test;
    root /var/www/laravel-v10/public; # 必须指向 public 目录
    index index.php index.html;

    # Laravel 官方推荐的优雅链接配置
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # 处理 PHP 请求
    location ~ \.php$ {
        fastcgi_pass tp-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # 禁止访问敏感文件
    location ~ /\.(?!well-known).* {
        deny all;
    }
}